add_custom_target(hex
  DEPENDS ${FULL_OUTPUT_NAME}
  COMMAND ${CMAKE_OBJCOPY} -v -Oihex ${EXECUTABLE_OUTPUT_PATH}/${FULL_OUTPUT_NAME} ${EXECUTABLE_OUTPUT_PATH}/${OUTPUT_NAME}.hex
)

if(${HAVE_CHECKSUM_TOOL})
  add_custom_target(bin
    DEPENDS ${FULL_OUTPUT_NAME}
    COMMAND ${CMAKE_OBJCOPY} -v -Obinary ${EXECUTABLE_OUTPUT_PATH}/${FULL_OUTPUT_NAME} ${EXECUTABLE_OUTPUT_PATH}/${OUTPUT_NAME}.bin
    COMMAND ${CHECKSUM_TOOL} -p ${DEVICE} -d ${EXECUTABLE_OUTPUT_PATH}/${OUTPUT_NAME}.bin
  )
else()
  add_custom_target(bin
    DEPENDS ${FULL_OUTPUT_NAME}
    COMMAND ${CMAKE_OBJCOPY} -v -Obinary ${EXECUTABLE_OUTPUT_PATH}/${FULL_OUTPUT_NAME} ${EXECUTABLE_OUTPUT_PATH}/${OUTPUT_NAME}.bin
  )
 endif()

add_custom_target(lst
  DEPENDS ${FULL_OUTPUT_NAME}
  COMMAND ${CMAKE_OBJDUMP} -x -D ${EXECUTABLE_OUTPUT_PATH}/${FULL_OUTPUT_NAME} > ${EXECUTABLE_OUTPUT_PATH}/${OUTPUT_NAME}.lst
)

if(${HAVE_OPENOCD})
  add_custom_target(flash
    DEPENDS ${FULL_OUTPUT_NAME}
    COMMAND make bin
    COMMAND ${OPENOCD_BINARY} -f ${CMAKE_SOURCE_DIR}/debug/${OPENOCD_CONFIG} -c "init" -c "halt 0" -c "flash write_image erase unlock" ${EXECUTABLE_OUTPUT_PATH}/cursada_mc2.axf  ${TARGET_DOWNLOAD_FLASH_BANK} bin -c "reset run" -c "shutdown"
  )
endif()